# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2
jobs:
  build:
    docker:
      # specify the version you desire here
      - image: circleci/node:8.10

      # Specify service dependencies here if necessary
      # CircleCI maintains a library of pre-built images
      # documented at https://circleci.com/docs/2.0/circleci-images/
      # - image: circleci/mongo:3.4.4

    working_directory: ~/repo

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
            - npm-dependencies-{{ checksum "package.json" }}
            # fallback to using the latest cache if no exact match is found
            - npm-dependencies-

      - run: npm install --no-optional

      - save_cache:
          paths:
            - node_modules
          key: npm-dependencies-{{ checksum "package.json" }}

      # run tests!
      - run: make test

      # Since there is no test codes yet, just perform production build.
      - run: make build

      # save artifacts
      - store_artifacts:
          paths: ./build
